name: securitycheck
description: A library to check whether your passwords are secure and strong.
version: 1.2.1
homepage: https://github.com/angeldollface/securitycheck
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  lint: ^2.0.1
